# Docs: https://www.gitpod.io/docs/41_Config_Gitpod_File
image: sharp6292/sharpbot-discord:gitpod

tasks:
  - command: echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - command: wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - command: apt-get update
  # rethinkdb -n pdrdb -d /data --bind 0.0.0.0 --server-tag default --http-port 28010 --driver-port 28015
  - command: apt-get install rethinkdb


