version: '3'
services:
  rdb:
    hostname: "rdb"
    image: rethinkdb:2.3.6
    volumes:
      - "db_data:/data"
    entrypoint: rethinkdb -n pdrdb -d /data --bind 0.0.0.0 --server-tag default --http-port 28010 --driver-port 28015

  sharpbot:
    hostname: "sharpbot"
    image: sharp6292/sharpbot-discord:latest
    environment:
      - SECRET=${SECRET:-XXX}
      - DEVMODE=${DEVMODE:-TRUE}
      - CICD=${CICD:-FALSE}
    restart: ${RESTART:-no}
    depends_on:
      - rdb

volumes:
  db_data: