version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.7.3-alpine3.8
    steps:
      - run: pip install flake8
      - run: python -m flake8

  tests:
    docker:
      - image: python:3.7.3-slim-stretch
      - image: rethinkdb:2.3.6

    steps:
      - checkout

      - run:
          name: "Prepare Tests"
          command: |
            pip install pipenv
            pipenv install --system
            echo "CICD=TRUE" > .env

      - run:
          name: "Run Tests"
          command: |
            cd project
            python -u run.py

      - store_artifacts:
          path: ./project/bot_testing/artifacts
          destination: artifacts

  build:
    docker:
      - image: docker:19.03

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: "Setup"
          command: |
            echo 'export IMAGE_TAG="${CIRCLE_PROJECT_REPONAME}:latest"' >> $BASH_ENV
            echo 'export IMAGE_TAG_CLOUD="${DOCKER_USER}/${IMAGE_TAG}"' >> $BASH_ENV
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            mkdir workspace

      - run:
          name: "Docker pull"
          command: |
            source $BASH_ENV
            docker pull ${IMAGE_TAG_CLOUD} || true

      - run:
          name: "Docker build"
          command: |
            source $BASH_ENV
            docker build --cache-from ${IMAGE_TAG_CLOUD} -f "Dockerfile" -t ${IMAGE_TAG_CLOUD} .

      - run:
          name: "Docker Save"
          command: |
            docker save --output ${CIRCLE_PROJECT_REPONAME}.tar ${IMAGE_TAG_CLOUD}
            cp ${CIRCLE_PROJECT_REPONAME}.tar ./workspace/${CIRCLE_PROJECT_REPONAME}.tar

      - persist_to_workspace:
          root: .
          paths:
            - ./workspace

  release:
    docker:
      - image: docker:19.03

    steps:
      - setup_remote_docker

      - checkout

      - attach_workspace:
          at: .

      - run:
          name: "Setup"
          command: |
            cd workspace
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker load --input ${CIRCLE_PROJECT_REPONAME}.tar

      - run:
          name: "Docker Save"
          command: |
            source $BASH_ENV
            docker push ${IMAGE_TAG_CLOUD}

workflows:
  version: 2
  workflow:
    jobs:
      - lint

      - tests

      - build

      - release:
          requires:
            - lint
            - tests
            - build
