version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.7.3-alpine3.8
    steps:
      - run: pip install flake8
      - run: python -m flake8

  tests:
    docker:
      - image: sharp6292/ci-pipenv
      - image: rethinkdb:2.3.6

    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: "Prepare Tests"
          command: |
            pipenv install
            echo "CICD=TRUE" > .env

      - run:
          name: "Run Tests"
          command: |
            cd project
            pipenv run python run.py

      - save_cache:
          paths:
            - ~/.local/share/virtualenvs/venv  # this path depends on where pipenv creates a virtualenv
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - store_artifacts:
          path: ./project/bot_testing/artifacts
          destination: artifacts

  build:
    docker:
      - image: docker:19.03

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: "Setup"
          command: |
            echo 'export IMAGE_TAG="${CIRCLE_PROJECT_REPONAME}:latest"' >> $BASH_ENV
            echo 'export IMAGE_TAG_CLOUD="${DOCKER_USER}/${IMAGE_TAG}"' >> $BASH_ENV
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            mkdir workspace

      - run:
          name: "Docker pull"
          command: |
            source $BASH_ENV
            docker pull ${IMAGE_TAG_CLOUD} || true

      - run:
          name: "Docker build"
          command: |
            source $BASH_ENV
            docker build --cache-from ${IMAGE_TAG_CLOUD} -f "Dockerfile" -t ${IMAGE_TAG_CLOUD} .

      - run:
          name: "Docker Save"
          command: |
            source $BASH_ENV
            docker save --output ${CIRCLE_PROJECT_REPONAME}.tar ${IMAGE_TAG_CLOUD}
            cp ${CIRCLE_PROJECT_REPONAME}.tar ./workspace/${CIRCLE_PROJECT_REPONAME}.tar

      - persist_to_workspace:
          root: .
          paths:
            - ./workspace

  release:
    docker:
      - image: docker:19.03

    steps:
      - checkout

      - setup_remote_docker

      - attach_workspace:
          at: .

      - run:
          name: "Setup"
          command: |
            echo 'export IMAGE_TAG="${CIRCLE_PROJECT_REPONAME}:latest"' >> $BASH_ENV
            echo 'export IMAGE_TAG_CLOUD="${DOCKER_USER}/${IMAGE_TAG}"' >> $BASH_ENV
            cd workspace
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker load --input ${CIRCLE_PROJECT_REPONAME}.tar

      - run:
          name: "Release"
          command: |
            source $BASH_ENV
            docker push ${IMAGE_TAG_CLOUD}

workflows:
  version: 2
  workflow:
    jobs:
      - lint

      - tests

      - build

      - release:
          requires:
            - lint
            - tests
            - build
