version: '3'
services:
  rdb:
    hostname: "rdb"
    image: rethinkdb:2.3.6
    entrypoint: rethinkdb -n pdrdb -d /data --bind 0.0.0.0 --server-tag default --http-port 28010 --driver-port 28015

  sharpbot:
    hostname: "sharpbot"
    image: sharpbot-discord:${BRANCH:-master}
    volumes:
      - project:/project
    depends_on:
      - rdb
    environment:
      - SECRET=${SECRET:-XXX}
      - DEVMODE=${DEVMODE:-TRUE}
      - CICD=${CICD:-TRUE}
    restart: ${RESTART:-no}

volumes:
    project:
      external:
        true