version: '3'
services:
  rdb:
    hostname: "rdb"
    image: rethinkdb:2.3.6
    volumes:
      - "../rethink_data:/data"
    entrypoint: rethinkdb -n pdrdb -d /data --bind 0.0.0.0 --server-tag default --http-port 28010 --driver-port 28015

  sharpbot:
    hostname: "sharpbot"
    image: sharpbot-discord:latest
    volumes:
      - project:/project
    depends_on:
      - rdb:rdb
    env_file:
      - ../.env

volumes:
    rdb:
    sharpbot:
    project:
      external:
        true